"use client";
import { useCallback, useEffect, useState } from "react";
type Idea={id:string;title:string;content:string;category:string;status:string;createdAt:string|number;updatedAt:string|number};
const categories=["Personnel","Projet","Créativité","Travail","À partager"];
const statuses=["Capturée","À explorer","Prometteuse","En projet","Réalisée"];
export default function Home(){
 const [ideas,setIdeas]=useState<Idea[]>([]),[text,setText]=useState(""),[view,setView]=useState<"today"|"library">("today"),[query,setQuery]=useState(""),[editing,setEditing]=useState<Idea|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=useCallback(async(q="")=>{setLoading(true);try{const r=await fetch(`/api/ideas${q?`?q=${encodeURIComponent(q)}`:""}`);const data=await r.json();if(!r.ok)throw new Error(data.error);setIdeas(data.ideas)}catch{setError("Impossible de charger tes idées pour le moment.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]); useEffect(()=>{if(view!=="library")return;const t=setTimeout(()=>load(query),250);return()=>clearTimeout(t)},[query,view,load]);
 async function capture(){const title=text.trim();if(!title)return;setSaving(true);setError("");try{const r=await fetch("/api/ideas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title})});const data=await r.json();if(!r.ok)throw new Error(data.error);setIdeas(v=>[data.idea,...v]);setText("")}catch{setError("L’idée n’a pas pu être enregistrée.")}finally{setSaving(false)}}
 async function update(form:FormData){if(!editing)return;setSaving(true);const payload={id:editing.id,title:String(form.get("title")),content:String(form.get("content")),category:String(form.get("category")),status:String(form.get("status"))};try{const r=await fetch("/api/ideas",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error);setIdeas(v=>v.map(i=>i.id===editing.id?data.idea:i));setEditing(null)}catch{setError("Les modifications n’ont pas été enregistrées.")}finally{setSaving(false)}}
 async function remove(){if(!editing||!confirm("Supprimer cette idée ?"))return;const id=editing.id;setEditing(null);const r=await fetch(`/api/ideas?id=${id}`,{method:"DELETE"});if(r.ok)setIdeas(v=>v.filter(i=>i.id!==id));else setError("La suppression a échoué.")}
 const date=new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
 return <main className="shell"><aside className="sidebar"><div className="brand"><span>é</span> étincelle</div><nav><button onClick={()=>setView("today")} className={`nav ${view==="today"?"active":""}`}><span>⌂</span>Aujourd’hui</button><button onClick={()=>setView("library")} className={`nav ${view==="library"?"active":""}`}><span>▤</span>Mes idées <b>{ideas.length}</b></button><button className="nav soon"><span>◇</span>Connexions</button><button className="nav soon"><span>♧</span>Mon jardin</button></nav><div className="sidebarFoot"><div className="streak"><span>✦</span><div><strong>{ideas.length} étincelle{ideas.length!==1?"s":""}</strong><small>Ton jardin prend vie</small></div></div><div className="privacy">● Sauvegarde active</div></div></aside>
 <section className="content"><header><p>{date}</p><span className="cloud">☁ Tout est enregistré</span></header>{error&&<div className="error">{error}<button onClick={()=>setError("")}>×</button></div>}
 {view==="today"?<><div className="hero"><span className="eyebrow">TON ESPACE DE PENSÉE</span><h1>Qu’est-ce qui te traverse<br/>l’esprit aujourd’hui ?</h1><p>Dépose une pensée, même imparfaite. Tu pourras la faire grandir plus tard.</p><div className="capture"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&(e.metaKey||e.ctrlKey))capture()}} placeholder="Écris ton idée ici…" aria-label="Nouvelle idée"/><div><span className="shortcut">Ctrl + Entrée</span><button className="save" disabled={saving||!text.trim()} onClick={capture}>{saving?"Enregistrement…":"Capturer"} <span>↗</span></button></div></div><div className="hint"><span>✦</span> Pas d’inspiration ? <button onClick={()=>setText("Et si je pouvais…")}>Lance-moi une piste</button></div></div><IdeaSection ideas={ideas.slice(0,3)} loading={loading} onOpen={setEditing} title="Idées récentes" onAll={()=>setView("library")}/></>:<section className="library"><span className="eyebrow">TA MÉMOIRE CRÉATIVE</span><div className="libraryHead"><div><h1>Toutes mes idées</h1><p>Retrouve, affine et transforme tes pensées.</p></div><button className="newIdea" onClick={()=>setView("today")}>+ Nouvelle idée</button></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans mes idées…"/></div><IdeaSection ideas={ideas} loading={loading} onOpen={setEditing} title=""/></section>}</section>
 {editing&&<div className="modalBack" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><form className="modal" action={update}><div className="modalTop"><span className="eyebrow">FAIRE GRANDIR L’IDÉE</span><button type="button" onClick={()=>setEditing(null)}>×</button></div><input className="titleInput" name="title" defaultValue={editing.title} required/><textarea className="contentInput" name="content" defaultValue={editing.content} placeholder="Ajoute du contexte, des pistes, une prochaine étape…"/><div className="fields"><label>Catégorie<select name="category" defaultValue={editing.category}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>État<select name="status" defaultValue={editing.status}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div><div className="modalActions"><button type="button" className="delete" onClick={remove}>Supprimer</button><button className="save" disabled={saving}>{saving?"Enregistrement…":"Enregistrer"}</button></div></form></div>}</main>
}
function IdeaSection({ideas,loading,onOpen,title,onAll}:{ideas:Idea[];loading:boolean;onOpen:(i:Idea)=>void;title:string;onAll?:()=>void}){return <section className="recent"><div className="sectionTitle"><div>{title&&<><span>TES DERNIÈRES ÉTINCELLES</span><h2>{title}</h2></>}</div>{onAll&&<button onClick={onAll}>Tout voir →</button>}</div>{loading?<div className="empty">Chargement de tes idées…</div>:ideas.length===0?<div className="empty"><strong>Ta prochaine étincelle commence ici.</strong><span>Capture une idée pour la retrouver dans cette bibliothèque.</span></div>:<div className="ideaGrid">{ideas.map((idea,index)=><article className="ideaCard" key={idea.id} onClick={()=>onOpen(idea)} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")onOpen(idea)}}><div className={`ideaIcon ${["sun","mint","lilac"][index%3]}`}>✦</div><span className="category">{idea.category}</span><h3>{idea.title}</h3><p>{new Date(idea.updatedAt).toLocaleDateString("fr-FR",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</p><div className="cardBottom"><span>{idea.status}</span><button aria-label="Ouvrir">↗</button></div></article>)}</div>}</section>}
